       01  C-LINE-STATE-INITIAL     CONSTANT 0.
       01  C-LINE-STATE-ONE-LEVEL   CONSTANT 1.
       01  C-LINE-STATE-INCREASING  CONSTANT 2.
       01  C-LINE-STATE-DECREASING  CONSTANT 3.
       01  C-LINE-STATE-UNSAFE      CONSTANT 4.
